2017-05-05 12:12:08,898 ERROR: Exception on / [GET] [in /home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/flaskbb/app.py", line 272, in update_lastseen
    if current_user.is_authenticated:
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/flask_login/utils.py", line 302, in _get_user
    current_app.login_manager._load_user()
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/flask_login/login_manager.py", line 317, in _load_user
    return self.reload_user()
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/flask_login/login_manager.py", line 279, in reload_user
    user = self.user_callback(user_id)
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/flaskbb/app.py", line 192, in load_user
    user_instance = User.query.filter_by(id=user_id).first()
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 496, in __get__
    mapper = orm.class_mapper(type)
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/sqlalchemy/orm/base.py", line 421, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/sqlalchemy/orm/base.py", line 400, in _inspect_mapped_class
    mapper._configure_all()
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1222, in _configure_all
    configure_mappers()
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2866, in configure_mappers
    mapper._post_configure_properties()
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1765, in _post_configure_properties
    prop.init()
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/sqlalchemy/orm/interfaces.py", line 184, in init
    self.do_init()
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1653, in do_init
    self._setup_join_conditions()
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1728, in _setup_join_conditions
    can_be_synced_fn=self._columns_are_mapped
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1986, in __init__
    self._determine_joins()
  File "/home/mansoor/pywork/catsanddogs/KnowYourPet/.venv/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 2090, in _determine_joins
    "specify a 'primaryjoin' expression." % self.prop)
NoForeignKeysError: Could not determine join condition between parent/child tables on relationship Pet.reminders - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
